### ISSUE TITLE
Project Feedback

### ISSUE THREAD

**Issue by GriffinMartin** [GriffinMartin/MI-449-SS17-740-js-firebase-intro-T4LtxO#1]
@egillespie Can you take a look at this? It's [hosted here](https://mart1444-kgucykegmdzxwt4ltxo.surge.sh/) and meets the following criteria:

- [x] Use [this code](https://gist.github.com/egillespie/942cc3aed19977590b431c10333736c2) as a foundation for your project
- [x] Your own Firebase project is used to store all of the site's messages
- [x] A message and its creation time are added to the database when Enter is pressed or Woof is clicked
- [x] Messages are stored in the database according to the structure in `model.json`
- [x] Anyone can edit any message by clicking the pencil icon, typing a new message, and pressing Enter
- [x] Anyone can delete any message by clicking the red X icon
- [x] When a message is added, edited, or deleted, _Recent woofs_ automatically updates for everyone viewing the page
- [x] Use the `TODO` comments in `woofer-db.js` as your guide for placing code

🎉 🎉🎉

**Comment by egillespie** [comment]
Hi @GriffinMartin, this is nearly perfect and good job working in arrow functions! 🎉 

The only thing I recommend fixing is your call to `deleteWoofRow`. Currently you are passing the key and value as two parameters, but `deleteWoofRow` only takes one parameter. Do you mind looking in `woofer-ui.js` at the declaration of `deleteWoofRow` and updating your code to only pass the requirement argument?

Let me know when you're ready for me to take another look! 🌮

**Comment by GriffinMartin** [comment]
@egillespie I think I fixed it! Thanks for the feedback 💯

**Comment by egillespie** [comment]
Cool, looks good! :shipit: 

The only other things I noticed that could be improved weren't very relevant to this project, but if you want to keep them in mind for the future:

1. Create a `.gitignore` file to exclude files such as `.DS_Store`.
2. Remove lines of code instead of commenting them out. One wrong keystroke could re-introduce code that you don't want!
